# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 2.0.1"

Vagrant.configure(2) do |config|
  # We're going to configure the VM networking using VirtualBox's host-only
  # network so that they can talk to each other and we can SSH to both.

  @node_defs = [
    { name: ENV["kubelet_name"], ip: ENV["kubelet_ip"] }
  ]

  #
  # Common configuration
  #
  config.ssh.username = ENV['ssh_username']
  config.ssh.password = ENV['ssh_password']
  config.vm.box       = ENV['box_name']
  config.vm.box_url   = ENV['box_path']

  config.vm.synced_folder ".", "/vagrant", disabled: true

  @node_defs.each do |node_def|
    config.vm.define node_def[:name] do |node|
      node.vm.network "private_network", ip: node_def[:ip]

      node.vm.provider :virtualbox do |p|
        p.gui    = false
        p.cpus   = 1
        p.memory = 1024
      end
    end
  end

end
