#!/usr/bin/env bash
set -e

# Make sure we're in the examples/localdev directory
cd $(dirname "${BASH_SOURCE[0]}")/..

source ../../lib/common
source hooks/lib/common

echo -e "${green}==================================================="
echo "Your environment is ready."
echo ""
echo "Connect via:"
echo ""
echo "  * ssh $kubelet_name"
echo ""
echo "==================================================="
