#!/usr/bin/env bash
set -e

script_path=$( dirname "${BASH_SOURCE[0]}" )
kickstart_cfg=$script_path/kickstart.cfg

# $lib_path is defined in script/lib/common
$lib_path/render ${kickstart_cfg}.template > $kickstart_cfg
