#!/usr/bin/env bash
set -e

# Make sure we're in the examples/localdev directory
cd $(dirname "${BASH_SOURCE[0]}")/../..

source ../../lib/common
source hooks/lib/common

echo "Re-importing box ${box_name}"

if vagrant box list | grep ${box_name}; then
    vagrant box remove --force ${box_name}
fi

vagrant box add --name ${box_name} ${box_path}
